#!/usr/bin/env ruby
require 'yaml'

scripts_dir = File.dirname File.realpath $0
DETECT_TABLET_MODE_SCRIPT_PATH="#{scripts_dir}/detect_tablet_mode"

def load_config!
  @config = YAML.load(File.read("#{ENV['HOME']}/.config/watch_tablet.yml"))
end

def config
  load_config! unless @config
  @config 
end

def detect_accels!
  prefix='/sys/bus/iio/devices/iio:device'
  ($display_accel_id, $keyboard_accel_id) = Dir[prefix+'*'].find_all{|x| File.read(x+"/name").chomp == 'accel_3d' }.map{|x| x.sub(prefix,'')}
  puts "Detected accelerometers: #$display_accel_id, #$keyboard_accel_id"
  if get_mode == 'tablet'
    puts "Swapping the order of accelerometers"
    $display_accel_id, $keyboard_accel_id = $keyboard_accel_id, $display_accel_id
  end
end

def get_mode
  `#{DETECT_TABLET_MODE_SCRIPT_PATH} #$display_accel_id #$keyboard_accel_id`.chomp
end

def activate_mode(mode)
  puts "Switching to #{mode} mode"
  if cmds = config['modes'][mode]
    cmds.each{|cmd| system cmd }
  end
end

def run_watcher
  detect_accels!
  old_mode = nil
  loop do
    new_mode = get_mode
    if old_mode != new_mode
      activate_mode(new_mode)
      old_mode = new_mode
    end
    sleep 0.5
  end
rescue Interrupt
end

run_watcher
