#!/usr/bin/env ruby
require 'yaml'

scripts_dir = File.dirname File.realpath $0
DETECT_TABLET_MODE_SCRIPT_PATH="#{scripts_dir}/detect_tablet_mode"

def accel_ids
  $accel_ids.join(' ')
end

def get_mode
  `#{DETECT_TABLET_MODE_SCRIPT_PATH} #{accel_ids}`.chomp
end

def detect_accels!
  prefix='/sys/bus/iio/devices/iio:device'
  $accel_ids = Dir[prefix+'*'].find_all{|x| File.read(x+"/name").chomp == 'accel_3d' }.map{|x| x.sub(prefix,'')}
  if $accel_ids.size == 2
    if get_mode == 'tablet'
      $accel_ids.reverse!
    end
  end
  puts accel_ids
end

detect_accels!
